import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    cardContainer: {
      width: '100%',
      height: 300,
      borderRadius: 80,
      display: 'flex',
      flexDirection: 'column',
      backgroundColor: '',
    },
    actionsGroup: {
      display: 'flex',
      justifyContent: 'space-around',
      alignSelf: 'flex-start',
      backgroundColor: 'transparent',
      flexDirection: 'row',
      width: '100%',
      paddingVertical: 10,
    },
    buttonLeft: {
      display: 'flex',
      height: 48,
      minWidth: 70,
      borderTopLeftRadius: 15,
      borderTopRightRadius: 40,
      borderBottomRightRadius: 20,
      borderBottomLeftRadius: 70,
      alignItems: 'center',
      justifyContent: 'center',
      paddingLeft: 25,
      paddingRight: 15,
    },
    buttonRight: {
      display: 'flex',
      minWidth: 47,
      height: 48,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 5,
      borderBottomRightRadius: 48,
      borderBottomLeftRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 10,
      paddingRight: 25,
    },
    buttonCapsul: {
      borderRadius: 100,
      height: 48,
      minWidth: 62,
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 15,
    },
    absolute: {
      position: 'absolute',
      top: 0,
      left: 0,
      bottom: 0,
      right: 0,
    },
    buttonText: {
      color: 'white',
      fontSize: 14,
    },
    gradientContainer: {
      width: 104,
      height: 50,
      borderRadius: 100,
      overflow: 'hidden',
    },
    box: {
      width: 102,
      height: 48,
      borderRadius: 100,
      backgroundColor: '#595959',
      overflow: 'hidden',
    },
    box1: {
      width: 70,
      height: 48,
      backgroundColor: 'rgba(0, 0, 0, 0.7)',
      shadowColor: 'green',
      shadowOffset: {width: 0, height: 4},
      shadowOpacity: 1,
      shadowRadius: 12,
      elevation: 5,
      overflow: 'hidden',
      justifyContent: 'center',
      alignItems: 'center',
      display: 'flex',
      borderTopLeftRadius: 5,
      borderTopRightRadius: 40,
      borderBottomRightRadius: 25,
      borderBottomLeftRadius: 70,
    },
    gradient1: {
      position: 'absolute',
      width: 70,
      height: 48,
      borderTopLeftRadius: 5,
      borderTopRightRadius: 40,
      borderBottomRightRadius: 25,
      borderBottomLeftRadius: 70,
    },
  });
